apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
    template:
        metadata:
            labels:
                app: db
        spec:
            initContainers:
                - name: fix-permissions
                  image: busybox
                  command:
                      ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
                  volumeMounts:
                      - name: db-storage
                        mountPath: /var/lib/postgresql/data
            containers:
                - name: postgres
                  image: postgres:13
                  env:
                      - name: PGDATA
                        value: /var/lib/postgresql/data/pgdata
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: POSTGRES_DB
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: POSTGRES_PASSWORD
                  volumeMounts:
                      - name: db-storage
                        mountPath: /var/lib/postgresql/data
                      - name: db-init-sql
                        mountPath: /docker-entrypoint-initdb.d/init.sql
                        subPath: init.sql
            volumes:
                - name: db-storage
                  persistentVolumeClaim:
                      claimName: db-pvc
                - name: db-init-sql
                  configMap:
                    name: db-init-sql
