apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    labels:
        app: api

type: Opaque
stringData:
    DB_USER: "postgres"
data:
    DB_PASS: VmlwaW5AMTIz
---
apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    labels:
        app: db

type: Opaque
stringData:
    POSTGRES_DB: "mydb"
    POSTGRES_USER: "postgres"
data:
    POSTGRES_PASSWORD: VmlwaW5AMTIz
